# Generated by Django 2.2.2 on 2019-06-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerboard', '0002_auto_20190605_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxinterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum', models.CharField(max_length=3)),
            ],
        ),
    ]
