# Generated by Django 2.2.2 on 2019-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerboard', '0003_maxinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='date_applied',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Applied'),
        ),
    ]
