# Generated by Django 2.2.2 on 2019-06-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerboard', '0004_interest_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxinterest',
            name='cutoff_date',
            field=models.DateField(auto_now=True, verbose_name='cutoff date'),
        ),
    ]
