# Generated by Django 2.2.2 on 2019-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerboard', '0005_maxinterest_cutoff_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxinterest',
            name='cutoff_date',
            field=models.DateTimeField(verbose_name='cutoff date'),
        ),
    ]
